#Para compilar com Clang++ rode o execute o makefile apenas com o argumento "all"
#Para compilar com G++ rode o execute o makefile apenas com o argumento "all CC=g++"

#compilador padrão
CC = clang++

all: prim

prim.exe: prim.cpp grafo.hpp heaps.hpp
	$(CC) -o prim.exe prim.cpp -Wall -Wextra
