#Para compilar com Clang++ rode o execute o makefile apenas com o argumento "all"
#Para compilar com G++ rode o execute o makefile apenas com o argumento "all CC=g++"

#compilador padrão
CC = clang++

all: bellmanFord

bellmanFord: bellmanFord.cpp grafo.hpp
	$(CC) -o bellmanFord.exe bellmanFord.cpp -Wall -Wextra